#!/bin/sh

# Start ssh-agent: https://wiki.archlinux.org/title/SSH_keys
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    #ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
    ssh-agent > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

# Start the wayland compositor
if [ -z "${DISPLAY}" ] && [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ] && [ "$(tty)" = "/dev/tty1" ]; then
  exec ~/scripts/startw Hyprland
fi

