#!/bin/sh

handle() {
  case $1 in
    workspace*)
      workspace=$(echo "$1" | tr -d -C '[:digit:]')
      if [ "$(hyprctl activewindow -j)" = "{}" ]; then
        ~/scripts/hyprland/focus-topleft-workspace
      fi

      ;;
  esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done

