#!/bin/sh
# Wrapper script for doas, to retry entering password if failed

for tries in 2 1 0; do
  /usr/bin/doas "$@"

  if [ $? = 0 ]; then break
  elif [ "${tries}" -eq 0 ]; then
    error '3 incorrect password attempts'
    exit 1
  fi

done

