#!/bin/sh
# Wrapper script for sudo, to forward it to doas

printf "Sudo wrapper was called with cmdline: $0 $@\n"
printf "Passthrough to doas? (sudo-specific flags may not work) [Y/n/c]: "
read ans

if [ "$ans" = "n" ]; then
  printf "OK\n"
elif [ "$ans" = "c" ]; then
  printf "Enter command to be evaluated: "
  read command
  eval $command
elif [ "$ans" = "s" ]; then
  /bin/sudo "$@"
else
  doas "$@"
fi


