#!/bin/sh

# Increment, decrement, or mute the volume and send a notification
# of the current volume level.

send_notification() {
  volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed -n 's/Volume: \([0-9.]*\).*/\1/p' | awk '{printf "%.0f", $1 * 100}')
  echo $volume
	notify-send -a "changevolume" -u low -r 9993 -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%"
}

case $1 in
up)
	# Set the volume on (if it was muted)
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
  wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
	send_notification "$1"
	;;
down)
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
  wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%-
	send_notification "$1"
	;;
mute)
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
  if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q "[MUTED]"; then
		notify-send -a "changevolume" -t 2000 -r 9993 -u low -i "volume-mute" "Muted"
  else 
		send_notification up
  fi
	;;
esac

