#!/bin/bash

systemctl --user import-environment DBUS_SESSION_BUS_ADDRESS DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XAUTHORITY QT_QPA_PLATFORMTHEME
dbus-update-activation-environment --systemd --all

sleep 0.5
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-gtk
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
/usr/lib/xdg-desktop-portal-gtk &
sleep 0.7
/usr/lib/xdg-desktop-portal &

