#!/bin/zsh

if [ -z "$1" ]; then
    echo "Pass environment and flags as arguments"
    exit
fi

cd ~

# XDG Session: https://man.sr.ht/~kennylevinsen/greetd/#how-to-set-xdg_session_typewayland
    export XDG_CURRENT_DESKTOP=Hyprland
    export XDG_SESSION_TYPE=wayland
    export XDG_SESSION_DESKTOP=Hyprland

# Force native wayland
    export MOZ_ENABLE_WAYLAND=1
    export GDK_BACKEND=wayland,x11
    export QT_QPA_PLATFORM="wayland;xcb"
    export SDL_VIDEODRIVER=wayland
    export CLUTTER_BACKEND=wayland
    
# Wayland fixes

    # Fix graphical java programs being blank
    export _JAVA_AWT_WM_NONREPARENTING=1

exec "$@"
exit

